const { chromium } = require('playwright');
const assert = require('node:assert/strict');
let browser;
(async()=>{
 browser = await chromium.launch({executablePath:process.env.PIRATES_BROWSER_EXECUTABLE || undefined,headless:true});
 const base=(process.env.PIRATES_SITE_URL || 'https://pirates.davideb.ch').replace(/\/$/,'');
 const deployment=await (await fetch(base+'/deployment.json')).json();
 const report=await (await fetch(base+'/releases/'+deployment.release+'/report.json')).json();
 const format=n=>n.toLocaleString('en-US');
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/#f-62cd60b098a1a0381e31');
 await page.locator('#total-functions').filter({hasText:format(report.metrics.matched_functions)+' / '+format(report.metrics.total_functions)}).waitFor();
 await page.locator('#function-status').filter({hasText:'Verified match'}).waitFor();
 assert.equal(await page.locator('.asm-row').count(),2);
 assert.equal(await page.locator('#save').isVisible(),false);
 await page.getByRole('tab',{name:'Candidate source',exact:true}).click();
 await page.locator('#source-content').filter({visible:true}).waitFor();
 assert.equal(await page.locator('#source-content').evaluate(e=>e.readOnly),true);
 assert.match(await page.locator('#source-content').inputValue(),/return false/);
 await page.getByRole('tab',{name:'Assembly diff',exact:true}).click();
 await page.getByRole('combobox',{name:'Function status',exact:true}).selectOption('matched');
 assert.match(await page.locator('#result-count').textContent(),new RegExp(format(report.metrics.matched_functions)+' functions'));
 await page.getByRole('combobox',{name:'Function status',exact:true}).selectOption('missing');
 assert.match(await page.locator('#result-count').textContent(),new RegExp(format(report.metrics.missing_candidates)+' functions'));
 await page.getByRole('combobox',{name:'Function status',exact:true}).selectOption('all');
 await page.getByRole('searchbox',{name:'Search functions or objects',exact:true}).fill('ApiSet');
 assert.match(await page.locator('#result-count').textContent(),/1 functions/);
 await page.getByRole('searchbox',{name:'Search functions or objects',exact:true}).fill('');
 await page.getByRole('button',{name:'Link details',exact:true}).click();
 await page.locator('#link-diagnostics').filter({hasText:/\S/}).waitFor();
 assert.equal(await page.locator('#link-reason').textContent(),report.linking.reason);
 const post=await page.request.post(base+'/api/source',{data:{content:'malicious edit'}});
 assert.equal(post.ok(),false);
 assert.equal((await page.request.get(base+'/Pirates-executable')).status(),404);
 if(process.env.PIRATES_BROWSER_SCREENSHOT) await page.screenshot({path:process.env.PIRATES_BROWSER_SCREENSHOT,fullPage:true});
 console.log('PASS: real server UI, source, filters, link diagnostics and write rejection');
 if(process.env.PIRATES_WAIT_FOR_REFRESH === '1') {
  console.log('READY: awaiting deployment refresh');
  await page.waitForEvent('framenavigated',{predicate: frame=>frame===page.mainFrame(),timeout:180000});
 await page.locator('#function-status').filter({hasText:'Verified match'}).waitFor();
 assert.equal(new URL(page.url()).hash,'#f-62cd60b098a1a0381e31');
 assert.equal(await page.locator('.asm-row').count(),2);
  console.log('PASS: automatic release refresh preserved the selected function');
 }
 await page.getByRole('combobox',{name:'Code or data',exact:true}).selectOption('data');
 await page.getByRole('combobox',{name:'Function status',exact:true}).selectOption('matched');
 await page.getByRole('searchbox',{name:'Search functions or objects',exact:true}).fill('npos');
 await page.getByRole('treeitem',{name:/npos/}).click();
 await page.locator('#function-status').filter({hasText:'Verified match'}).waitFor();
 await page.getByRole('combobox',{name:'Data display format',exact:true}).selectOption('ascii');
 assert.match(await page.locator('#function-meta').textContent(),/4 bytes/);

 await page.locator('#map-filter').fill('PVRShellAPI.o');
 await page.locator('#map-summary').filter({hasText:'1 objects'}).waitFor();
 const canvas=page.locator('#progress-map');
 const green=await canvas.evaluate(e=>{const c=e.getContext('2d');return [...c.getImageData(e.width/2,e.height/2,1,1).data]});
 assert.ok(green[1]>green[0]+50);
 await canvas.focus();await page.keyboard.press('Enter');
 await page.locator('#map-location').filter({hasText:'PVRShellAPI.o'}).waitFor();
 await page.locator('#map-summary').filter({hasText:'1 functions'}).waitFor();
 await page.keyboard.press('Enter');
 await page.locator('#function-status').filter({hasText:'Verified match'}).waitFor();
 assert.equal(new URL(page.url()).hash,'#f-62cd60b098a1a0381e31');
 await page.locator('#map-back').click();
 await page.locator('#map-filter').fill('');
 await page.locator('#map-metric').selectOption('fuzzy');
 await page.locator('#map-explanation').filter({hasText:'does not prove byte equality'}).waitFor();
 await page.locator('#map-metric').selectOption('linking');
 await page.locator('#map-explanation').filter({hasText:'Diagnostic subset links do not contribute'}).waitFor();
 if(report.linking.state!=='verified') {
   const grey=await canvas.evaluate(e=>[...e.getContext('2d').getImageData(e.width/2,e.height/2,1,1).data]);
   assert.ok(grey[1]-grey[0]<15);
 }
 await page.locator('#map-metric').selectOption('data');
 await page.locator('#map-explanation').filter({hasText:'padding and zero-fill'}).waitFor();
 await page.locator('#map-category').selectOption('libOGLES2Tools.a');
 await page.locator('#map-summary').filter({hasText:'objects'}).waitFor();
 await page.locator('#map-category').selectOption('');
 await page.locator('#map-metric').selectOption('exact');
 await page.setViewportSize({width:390,height:844});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
 if(process.env.PIRATES_BROWSER_SCREENSHOT) await page.screenshot({path:process.env.PIRATES_BROWSER_SCREENSHOT.replace(/\.png$/,'-mobile.png'),fullPage:true});
 console.log('PASS: treemap color, object/function drill-down, exact/fuzzy/data/linking modes, archive filter, keyboard navigation and mobile layout');

 assert.deepEqual(errors,[]);
 console.log('PASS: exact data view works; zero browser errors');
 await browser.close();
})().catch(async e=>{console.error(e);await browser?.close();process.exit(1)});
