const { chromium } = require('playwright');
const assert = require('node:assert/strict');
let browser;
(async()=>{
 browser = await chromium.launch({executablePath:process.env.PIRATES_BROWSER_EXECUTABLE || undefined,headless:true});
 const base=(process.env.PIRATES_SITE_URL || 'https://pirates.davideb.ch').replace(/\/$/,'');
 const deployment=await (await fetch(base+'/deployment.json')).json();
 const report=await (await fetch(base+'/releases/'+deployment.release+'/report.json')).json();
 const format=n=>n.toLocaleString('en-US');
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 await page.goto(base+'/#f-62cd60b098a1a0381e31');
 await page.locator('#total-functions').filter({hasText:format(report.metrics.matched_functions)+' / '+format(report.metrics.total_functions)}).waitFor();
 await page.locator('#function-status').filter({hasText:'Verified match'}).waitFor();
 assert.equal(await page.locator('.asm-row').count(),2);
 assert.equal(await page.locator('#save').isVisible(),false);
 await page.getByRole('tab',{name:'Candidate source',exact:true}).click();
 await page.locator('#source-content').filter({visible:true}).waitFor();
 assert.equal(await page.locator('#source-content').evaluate(e=>e.readOnly),true);
 assert.match(await page.locator('#source-content').inputValue(),/return false/);
 await page.getByRole('tab',{name:'Assembly diff',exact:true}).click();
 await page.getByRole('combobox',{name:'Function status',exact:true}).selectOption('matched');
 assert.match(await page.locator('#result-count').textContent(),new RegExp(format(report.metrics.matched_functions)+' functions'));
 await page.getByRole('combobox',{name:'Function status',exact:true}).selectOption('missing');
 assert.match(await page.locator('#result-count').textContent(),new RegExp(format(report.metrics.missing_candidates)+' functions'));
 await page.getByRole('combobox',{name:'Function status',exact:true}).selectOption('all');
 await page.getByRole('searchbox',{name:'Search functions or objects',exact:true}).fill('ApiSet');
 assert.match(await page.locator('#result-count').textContent(),/1 functions/);
 await page.getByRole('searchbox',{name:'Search functions or objects',exact:true}).fill('');
 await page.getByRole('button',{name:'Link details',exact:true}).click();
 await page.locator('#link-diagnostics').filter({hasText:/\S/}).waitFor();
 assert.equal(await page.locator('#link-reason').textContent(),report.linking.reason);
 const post=await page.request.post(base+'/api/source',{data:{content:'malicious edit'}});
 assert.equal(post.ok(),false);
 assert.equal((await page.request.get(base+'/Pirates-executable')).status(),404);
 if(process.env.PIRATES_BROWSER_SCREENSHOT) await page.screenshot({path:process.env.PIRATES_BROWSER_SCREENSHOT,fullPage:true});
 console.log('PASS: real server UI, source, filters, link diagnostics and write rejection');
 if(process.env.PIRATES_WAIT_FOR_REFRESH === '1') {
  console.log('READY: awaiting deployment refresh');
  await page.waitForEvent('framenavigated',{predicate: frame=>frame===page.mainFrame(),timeout:180000});
 await page.locator('#function-status').filter({hasText:'Verified match'}).waitFor();
 assert.equal(new URL(page.url()).hash,'#f-62cd60b098a1a0381e31');
 assert.equal(await page.locator('.asm-row').count(),2);
  console.log('PASS: automatic release refresh preserved the selected function');
 }
 await page.getByRole('combobox',{name:'Code or data',exact:true}).selectOption('data');
 await page.getByRole('combobox',{name:'Function status',exact:true}).selectOption('matched');
 await page.getByRole('searchbox',{name:'Search functions or objects',exact:true}).fill('npos');
 await page.getByRole('treeitem',{name:/npos/}).click();
 await page.locator('#function-status').filter({hasText:'Verified match'}).waitFor();
 await page.getByRole('combobox',{name:'Data display format',exact:true}).selectOption('ascii');
 assert.match(await page.locator('#function-meta').textContent(),/4 bytes/);
 assert.deepEqual(errors,[]);
 console.log('PASS: exact data view works; zero browser errors');
 await browser.close();
})().catch(async e=>{console.error(e);await browser?.close();process.exit(1)});
