import argparse
import json
import hashlib
import shlex
import sys
from pathlib import Path
from .compiler import fingerprint, command, language_flags
from .sdk import header_flags
from .inputs import import_ipa, import_fixture
from .util import load_json, write_json, ToolError, local_path, sha256


def ninja_path(path):
    text = str(path)
    if '\n' in text or '\r' in text:
        raise ToolError('Newlines in paths are unsupported')
    return text.replace('$', '$$').replace(' ', '$ ').replace(':', '$:')


def configure(root, ipa=None, fixture=None, candidates=None, profile=None, sdk=None):
    root = Path(root).resolve()
    old_path = root / 'build/config.json'
    if ipa:
        provenance, inventory = import_ipa(ipa, root, load_json(root / 'config/identity.json'))
    elif fixture:
        provenance, inventory = import_fixture(fixture, root)
    else:
        if not old_path.exists():
            raise ToolError('Import inputs first: python configure.py --ipa <path>')
        old = load_json(old_path)
        provenance = old['provenance']
        if sha256(root / provenance['input']) != provenance['executable_sha256']:
            raise ToolError('Imported original executable hash mismatch')
        from .inventory import recover
        from .macho import MachO
        inventory = recover(MachO((root / provenance['input']).read_bytes()))
        candidates = candidates or old['candidates_path']
        profile = profile or old['profile_path']
        sdk = sdk or old.get('sdk')
    candidates = candidates or 'config/candidates.json'
    profile = profile or 'config/compiler.json'
    cpath, ppath = local_path(root, candidates), local_path(root, profile)
    manifest, compiler = load_json(cpath), load_json(ppath)
    if manifest.get('version') != 1 or not isinstance(manifest.get('units'), list):
        raise ToolError('Candidates manifest must have version 1 and a units array')
    if compiler['family'] == 'clang-fixture' and provenance['kind'] != 'synthetic' and manifest['units']:
        raise ToolError('Modern Clang candidates are restricted to synthetic inputs')
    group_ids = {g['id'] for g in inventory['groups']}
    function_groups = {f['id']: f['group_id'] for f in inventory['functions']}
    units, seen = [], set()
    for unit in manifest['units']:
        gid, source = unit['group_id'], unit['source']
        if gid not in group_ids or gid in seen:
            raise ToolError('Unknown or duplicate original object group: ' + gid)
        seen.add(gid)
        path = local_path(root, source)
        if path.suffix.lower() not in ('.c', '.cc', '.cpp', '.cxx', '.m', '.mm'):
            raise ToolError('Candidates must be C/C++/Objective-C source, not assembly or original bytes')
        if not isinstance(unit.get('flags', []), list) or not all(isinstance(x, str) for x in unit.get('flags', [])):
            raise ToolError('Unit flags must be a string array')
        if 'sdk_required' in unit and not isinstance(unit['sdk_required'], bool):
            raise ToolError('Unit sdk_required must be a boolean')
        for fid in unit.get('functions', {}):
            if function_groups.get(fid) != gid:
                raise ToolError('Function mapping must belong to its original object group: ' + fid)
        if not all(isinstance(v, int) and 0 <= v <= 0xffffffff for table in unit.get('placements', {}).values() for v in table.values()):
            raise ToolError('Placements must map symbols/sections to explicit 32-bit addresses')
        units.append({**unit, 'flags': unit.get('flags', []), 'id': gid})
    if sdk:
        sdk = str(Path(sdk).resolve())
    config = {'version': 1, 'provenance': provenance, 'candidates_path': str(cpath.relative_to(root)),
              'profile_path': str(ppath.relative_to(root)), 'compiler': compiler, 'sdk': sdk,
              'compiler_fingerprint': fingerprint(compiler, root, sdk), 'units': sorted(units, key=lambda u: u['id'])}
    if provenance['kind'] == 'game':
        lock = load_json(root / 'config/inventory-lock.json')
        digest = hashlib.sha256((json.dumps(inventory, indent=2, sort_keys=True, ensure_ascii=True) + '\n').encode()).hexdigest()
        if digest != lock['inventory_sha256'] or provenance['executable_sha256'] != lock['input_sha256']:
            raise ToolError('Inventory differs from the verified inventory lock; investigate missing records or changed boundaries')
    write_json(root / 'build/inventory.json', inventory)
    config['inventory_sha256'] = sha256(root / 'build/inventory.json')
    write_json(old_path, config)
    compile_commands = []
    py = shlex.quote(sys.executable).replace('$', '$$')
    script = 'tools/build.py'
    lines = ['# Generated by configure.py; edit config/candidates.json instead.', 'ninja_required_version = 1.10',
             'rule compile', f'  command = {py} {script} compile $unit', '  description = COMPILE $source',
             '  depfile = $depfile', '  deps = gcc', '  restat = 1', 'rule report',
             f'  command = {py} {script} report', '  description = COMPARE + REPORT', '  restat = 1',
             'rule configure', f'  command = {py} configure.py', '  generator = 1', '  restat = 1']
    tool_files = sorted([p.relative_to(root) for p in (root / 'tools/pirates').glob('*.py')] + [Path('tools/build.py')])
    implicit = ' '.join(ninja_path(p) for p in tool_files)
    dependencies = []
    if sdk:
        sdk_arg = shlex.quote(sdk).replace('$', '$$')
        lines += ['rule sdkcheck', f'  command = {py} tools/sdk.py stamp --sdk {sdk_arg}',
                  '  restat = 1', 'build sdk_check: phony',
                  'build build/sdk-identity.json: sdkcheck sdk_check | tools/sdk.py tools/pirates/sdk.py']
        dependencies.append('build/sdk-identity.json')
    sdk_dependency = 'build/sdk-identity.json ' if sdk else ''
    for unit in config['units']:
        uid = unit['id']
        output = f'build/units/{uid}.compile.json'
        dependencies.append(output)
        lines += [f'build {output}: compile {ninja_path(unit["source"])} | build/config.json {sdk_dependency}{implicit}',
                  f'  unit = {uid}', f'  source = {ninja_path(unit["source"])}', f'  depfile = build/units/{uid}.d']
        language = language_flags(unit['source'])
        editor_flags = ['-std=gnu++98' if language[1] in ('c++', 'objective-c++') else '-std=gnu89'] if compiler.get('editor_command') else []
        flags = language + editor_flags + compiler['flags'] + unit['flags']
        if sdk:
            flags += header_flags(compiler, sdk, unit['source'], editor=True)
            flags = [flag.replace('/sdk/', sdk + '/') for flag in flags]
        try:
            editor_command = compiler.get('editor_command') or command(compiler, root, sdk)
        except ToolError:
            editor_command = ['llvm-g++']  # Intended historical command; Ninja records the concrete compiler failure.
        compile_commands.append({'directory': str(root), 'file': str(local_path(root, unit['source'])),
                                 'arguments': editor_command + flags + ['-c', unit['source'], '-o', f'build/units/{uid}.o']})
    lines += ['build build/report.json build/objdiff-report.json: report build/inventory.json build/config.json build/inputs/Pirates '
              + ' '.join(dependencies) + ' | ' + implicit,
              'build build.ninja: configure ' + ninja_path(config['candidates_path']) + ' ' + ninja_path(config['profile_path'])
              + ' configure.py tools/pirates/configure.py config/identity.json'
              + (' config/inventory-lock.json' if provenance['kind'] == 'game' else ''), 'default build/report.json']
    (root / 'build.ninja').write_text('\n'.join(lines) + '\n')
    write_json(root / 'compile_commands.json', compile_commands)
    return config, inventory


def main(root):
    parser = argparse.ArgumentParser(description='Verify Pirates IPA and configure incremental matching tools')
    inputs = parser.add_mutually_exclusive_group()
    inputs.add_argument('--ipa', type=Path)
    inputs.add_argument('--fixture', type=Path, help='Synthetic tests/demo only; never counts as game progress')
    parser.add_argument('--candidates')
    parser.add_argument('--profile')
    parser.add_argument('--sdk', type=Path, help='Locally supplied iPhoneOS5.1.sdk')
    args = parser.parse_args()
    try:
        config, inventory = configure(root, **vars(args))
        print(f'{len(inventory["functions"]):,} functions / {len(inventory["groups"])} original object groups; {len(config["units"])} candidate units')
        info = config['compiler_fingerprint']
        print('Historical compiler: ' + ('validated cross-build (exact original equivalence unproven)' if info['validated'] else 'UNVALIDATED — ' + (info['reason'] or 'missing evidence')))
    except (ToolError, OSError, KeyError, json.JSONDecodeError) as e:
        parser.exit(1, str(e) + '\n')
