"""Deterministic native function report and objdiff protobuf-JSON adapter."""
from collections import Counter, defaultdict


def covered_bytes(functions):
    ranges = defaultdict(list)
    for f in functions:
        if f['size']:
            ranges[f['section']].append((f['address'], f['address'] + f['size']))
    total = 0
    for spans in ranges.values():
        end = -1
        for a, b in sorted(spans):
            total += max(0, b - max(a, end))
            end = max(end, b)
    return total


def metrics(functions):
    counts = Counter(f['status'] for f in functions)
    matched = [f for f in functions if f['status'] == 'matched']
    similar = [f for f in functions if f['similarity'] is not None]
    denom = covered_bytes(functions)
    return {'total_functions': len(functions), 'total_function_bytes': denom,
            'matched_functions': len(matched), 'matched_bytes': covered_bytes(matched),
            'missing_candidates': counts['missing'], 'unresolved_comparisons': counts['unresolved'],
            'different_functions': counts['different'], 'compile_errors': counts['compile_error'],
            'similarity_percent': round(sum((f['size'] or 0) * (f['similarity'] or 0) for f in functions) / sum(f['size'] or 0 for f in functions), 4) if any(f['size'] for f in functions) else 0,
            'compared_similarity_percent': round(sum(f['similarity'] for f in similar) / len(similar), 4) if similar else None}


def native_report(inventory, config, functions, units, compiler):
    return {'version': 1, 'kind': config['provenance']['kind'], 'architecture': 'armv7',
            'input_sha256': config['provenance']['executable_sha256'], 'inventory_sha256': config['inventory_sha256'],
            'coverage': inventory['coverage'], 'compiler': compiler,
            'profile': {k: v for k, v in config['compiler'].items() if k not in ('command', 'validation')},
            'metrics': metrics(functions), 'functions': functions, 'units': units,
            'linking': {'supported': False, 'complete_code': 0, 'complete_data': 0, 'complete_units': 0,
                        'reason': 'This milestone compares functions; it does not link a full-game replacement.'}}


def objdiff_adapter(report):
    """Proto JSON field names/types, pinned to the schema in toolchain/sources.lock.json.

    uint64 values are strings as prescribed by protobuf JSON. Complete/linking
    measures stay zero. Fuzzy score is assembly similarity, never byte evidence.
    """
    groups = defaultdict(list)
    for f in report['functions']:
        groups[f['group_id']].append(f)

    def measures(functions, units):
        m = metrics(functions)
        total, matched = m['total_function_bytes'], m['matched_bytes']
        n, exact = m['total_functions'], m['matched_functions']
        return {'fuzzyMatchPercent': m['similarity_percent'], 'totalCode': str(total), 'matchedCode': str(matched),
                'matchedCodePercent': round(100 * matched / total, 4) if total else 0,
                'totalData': '0', 'matchedData': '0', 'matchedDataPercent': 0,
                'totalFunctions': n, 'matchedFunctions': exact,
                'matchedFunctionsPercent': round(100 * exact / n, 4) if n else 0,
                'completeCode': '0', 'completeCodePercent': 0, 'completeData': '0', 'completeDataPercent': 0,
                'totalUnits': units, 'completeUnits': 0}

    return {'version': 2, 'measures': measures(report['functions'], len(report['units'])), 'categories': [],
            'units': [{'name': u['object_path'], 'measures': measures(groups[u['id']], 1), 'sections': [],
                       'functions': [{'name': f['symbol'], 'size': str(f['size'] or 0),
                                      'fuzzyMatchPercent': f['similarity'] or 0,
                                      'address': str(f['section_offset']), 'metadata': {'virtualAddress': str(f['address'])}}
                                     for f in groups[u['id']]],
                       'metadata': {'complete': False, 'sourcePath': u.get('source') or u['source_path'],
                                    'autoGenerated': False}} for u in report['units']]}


def regression(base, head):
    """Fail on loss of verified evidence, build health, or inventory coverage."""
    failures, newly_matched, improvements, regressions = [], [], [], []
    same = ('kind', 'input_sha256', 'inventory_sha256', 'profile', 'compiler')
    for key in same:
        if base[key] != head[key]:
            failures.append('Base/head do not share identical ' + key)
    if base.get('sdk') != head.get('sdk'):
        failures.append('Base/head do not share identical SDK content')
    previous = {f['id']: f for f in base['functions']}
    current = {f['id']: f for f in head['functions']}
    if set(previous) - set(current):
        failures.append('Inventory coverage disappeared: ' + ', '.join(sorted(set(previous) - set(current))))
    if base['coverage'] != head['coverage']:
        failures.append('Inventory coverage changed')
    for unit in head['units']:
        if unit.get('error') or (unit.get('compile') or {}).get('status') == 'compile_error':
            failures.append('Candidate unit does not compile: ' + unit['id'])
    if {u['id'] for u in base['units']} - {u['id'] for u in head['units']}:
        failures.append('Original object group coverage disappeared')
    for fid, f in sorted(current.items()):
        old = previous.get(fid)
        if f['status'] == 'compile_error':
            failures.append('Candidate does not compile: ' + fid)
        if old and old['status'] == 'matched' and f['status'] != 'matched':
            failures.append('Verified match regressed: ' + fid)
            regressions.append(fid)
        if f['status'] == 'matched' and (not old or old['status'] != 'matched'):
            newly_matched.append(fid)
        before, after = (old or {}).get('similarity'), f.get('similarity')
        if before is not None and after is not None:
            if after > before:
                improvements.append({'id': fid, 'before': before, 'after': after})
            elif after < before:
                regressions.append(fid)
        elif before is not None and after is None and fid not in regressions:
            regressions.append(fid)
    return {'failures': sorted(set(failures)), 'newly_matched': newly_matched,
            'improvements': improvements, 'regressions': sorted(set(regressions))}


def summary(base, head, delta):
    lines = ['## Pirates! function matching', '', '| Measure | Base | Head |', '|---|---:|---:|']
    for key in ('matched_bytes', 'matched_functions', 'missing_candidates', 'unresolved_comparisons', 'compile_errors', 'similarity_percent'):
        lines.append(f'| {key.replace("_", " ")} | {base["metrics"][key]} | {head["metrics"][key]} |')
    lines += ['', 'Full-game linking: **not implemented; 0 completed units**.', '',
              f'New verified matches: {len(delta["newly_matched"])}. Improvements: {len(delta["improvements"])}. Regressions: {len(delta["regressions"])}.', '']
    names = {f['id']: f['symbol'] for f in head['functions']}
    for title, values in [('New verified matches', delta['newly_matched']), ('Regressions', delta['regressions'])]:
        if values:
            lines += [f'### {title}', ''] + ['- `' + v + '` ' + names.get(v, '') for v in values]
    if delta['improvements']:
        lines += ['### Similarity improvements', ''] + [f'- `{v["id"]}`: {v["before"]}% → {v["after"]}%' for v in delta['improvements']]
    if delta['failures']:
        lines += ['', '### Failing checks', ''] + ['- ' + x for x in delta['failures']]
    return '\n'.join(lines) + '\n'
